server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://config-server:8888"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: https://auth-service-l1td.onrender.com
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: https://user-service-2c2u.onrender.com
          predicates:
            - Path=/api/users/**
        - id: chat-service
          uri: https://chat-service-4dpg.onrender.com
          predicates:
            - Path=/api/chats/**
        - id: group-service
          uri: https://group-service-eiwd.onrender.com
          predicates:
            - Path=/api/groups/**
        - id: media-service
          uri: https://media-service-2xxr.onrender.com
          predicates:
            - Path=/api/media/**
        - id: presence-service
          uri: https://presence-service-z1hn.onrender.com
          predicates:
            - Path=/api/presence/**
        - id: notification-service
          uri: https://notification-service-msh6.onrender.com
          predicates:
            - Path=/api/notifications/**
        - id: audit-service
          uri: https://audit-service-jm2v.onrender.com
          predicates:
            - Path=/api/audit/**
        - id: analytics-service
          uri: https://analytics-service-jekk.onrender.com
          predicates:
            - Path=/api/analytics/**
        - id: chat-ws
          uri: wss://chat-service-4dpg.onrender.com
          predicates:
            - Path=/ws/chat/**
        - id: group-ws
          uri: wss://group-service-eiwd.onrender.com
          predicates:
            - Path=/ws/group/**
        - id: presence-ws
          uri: wss://presence-service-z1hn.onrender.com
          predicates:
            - Path=/ws/presence/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka/}
